name: SpecFlow Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Tests/saraguNandini.csproj

      - name: Build
        run: dotnet build Tests/saraguNandini.csproj --no-restore

      - name: Install Playwright
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install

      - name: Run tests
        run: dotnet test Tests/saraguNandini.csproj --no-build

